// What the Codex and Claude Code readers share: the chat they produce, streaming their JSONL, and the rules that turn
// another agent's turns into pi messages (harness text left out, long outputs trimmed, tool names mapped to pi's).
import { createReadStream } from "node:fs";
import { open } from "node:fs/promises";
import type { ImportSource } from "../../shared/chat-import";
import type { AssistantMessage, TextContent, ThinkingContent, ToolCall, ToolResultMessage, UserMessage } from "../../shared/protocol";
import { JsonlSplitter } from "../jsonl";

/** A chat found in another agent's history, before it is read in full. */
export interface SourceChat {
  source: ImportSource;
  id: string;
  file: string;
  cwd: string;
  title?: string;
  createdAt: number;
  /** The source file's mtime: the chat's last activity. */
  mtimeMs: number;
  size: number;
}

export type ImportedEntry =
  | { kind: "message"; message: UserMessage | AssistantMessage | ToolResultMessage }
  /** The source compacted its context here: pi starts the model's context from this summary on. */
  | { kind: "compaction"; summary: string; timestamp: number };

/** Thrown while reading a chat that turns out not to be a person's (a claude-bridge session the sample missed). */
export class NotAPersonsChat extends Error {}

/** Characters of a tool's output kept: the start and the end, which hold the command echo and the verdict. */
export const OUTPUT_LIMIT = 4_000;
/** Characters of one string argument kept (a written file, a patch). */
export const ARGUMENT_LIMIT = 16_000;

export function trimText(text: string, limit = OUTPUT_LIMIT): string {
  if (text.length <= limit) return text;
  const head = Math.floor(limit * 0.75);
  const tail = limit - head;
  return `${text.slice(0, head)}\n\n… ${text.length - limit} characters not imported …\n\n${text.slice(-tail)}`;
}

export const IMAGE_PLACEHOLDER = "(image not imported)";

/** Each JSON record of a JSONL file, streamed (transcripts reach hundreds of MB); lines that do not parse are skipped. */
export async function* jsonRecords(file: string): AsyncGenerator<Record<string, any>> {
  const splitter = new JsonlSplitter();
  for await (const chunk of createReadStream(file)) {
    for (const line of splitter.push(chunk as Buffer)) {
      const record = parseLine(line);
      if (record) yield record;
    }
  }
  for (const line of splitter.end()) {
    const record = parseLine(line);
    if (record) yield record;
  }
}

/** The first `bytes` and last `tailBytes` of a file as whole lines: a cheap look at a transcript's metadata. */
export async function sampleLines(file: string, size: number, bytes: number, tailBytes = 0): Promise<{ head: string[]; tail: string[] }> {
  const handle = await open(file, "r");
  try {
    const read = async (start: number, length: number) => {
      const buffer = Buffer.alloc(length);
      const { bytesRead } = await handle.read(buffer, 0, length, start);
      return buffer.subarray(0, bytesRead).toString("utf8");
    };
    if (size <= bytes + tailBytes) return { head: (await read(0, size)).split("\n").filter(Boolean), tail: [] };
    // The head's last line and the tail's first line are cut; drop them.
    const head = (await read(0, bytes)).split("\n").slice(0, -1).filter(Boolean);
    const tail = tailBytes > 0 ? (await read(size - tailBytes, tailBytes)).split("\n").slice(1).filter(Boolean) : [];
    return { head, tail };
  } finally {
    await handle.close();
  }
}

export function parseLine(line: string): Record<string, any> | undefined {
  try {
    const value = JSON.parse(line);
    return value && typeof value === "object" ? value : undefined;
  } catch {
    return undefined;
  }
}

/** A part that is one whole tag (`<environment_context>…</environment_context>`), or a lone opening or closing tag. */
const WRAPPED = /^<([A-Za-z][\w:-]*)(?:\s[^>]*)?>[\s\S]*<\/\1>$/;
const LONE_TAG = /^<\/?[A-Za-z][\w:-]*(?:\s[^>]*)?>$/;
/** Instructions harnesses put in the user's turn as plain text. */
const INJECTED_PREFIXES = ["# AGENTS.md instructions", "Caveat: The messages below were generated by the user", "[Request interrupted by user"];

/**
 * Text the agent's harness wrote into the user's turn (project instructions, environment, reminders, attachments'
 * wrappers) rather than the person: a part that is exactly one tag, so new kinds of injected blocks drop too.
 */
export function isInjectedText(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return true;
  if (INJECTED_PREFIXES.some((prefix) => trimmed.startsWith(prefix))) return true;
  return WRAPPED.test(trimmed) || LONE_TAG.test(trimmed);
}

/** A user message from the parts a person wrote, or undefined when every part was the harness's. */
export function userMessage(parts: { text?: string; image?: true }[], timestamp: number): UserMessage | undefined {
  const content: TextContent[] = [];
  let images = 0;
  for (const part of parts) {
    if (part.image) images++;
    else if (part.text !== undefined && !isInjectedText(part.text)) content.push({ type: "text", text: part.text });
  }
  if (content.length === 0 && images === 0) return undefined;
  if (images > 0) content.push({ type: "text", text: images === 1 ? IMAGE_PLACEHOLDER : `(${images} images not imported)` });
  return { role: "user", content, timestamp };
}

const ZERO_USAGE = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } };

/**
 * An answer from another agent. Its provider is the agent's name, never a pi provider, so pi always treats it as
 * another model's turn when the chat continues: thinking becomes plain text and tool call ids are normalized.
 */
export function assistantMessage(source: ImportSource, api: string, model: string, timestamp: number): AssistantMessage {
  return { role: "assistant", content: [], api, provider: source === "codex" ? "codex" : "claude-code", model, usage: { ...ZERO_USAGE, cost: { ...ZERO_USAGE.cost } }, stopReason: "stop", timestamp };
}

export function thinking(text: string): ThinkingContent | undefined {
  return text.trim() ? { type: "thinking", thinking: text } : undefined;
}

export function toolResult(call: Pick<ToolCall, "id" | "name">, text: string, isError: boolean, timestamp: number): ToolResultMessage {
  return { role: "toolResult", toolCallId: call.id, toolName: call.name, content: [{ type: "text", text: trimText(text) }], isError, timestamp };
}

function trimArguments(args: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(args)) out[key] = typeof value === "string" ? trimText(value, ARGUMENT_LIMIT) : value;
  return out;
}

const str = (value: unknown): string | undefined => (typeof value === "string" ? value : undefined);

/** `["bash", "-lc", "script"]` -> `script`; any other argv joined with spaces. */
function commandLine(command: unknown): string | undefined {
  if (typeof command === "string") return command;
  if (!Array.isArray(command) || !command.every((part) => typeof part === "string")) return undefined;
  const argv = command as string[];
  if (argv.length === 3 && /(^|\/)(ba|z)?sh$/.test(argv[0] ?? "") && /^-l?c$/.test(argv[1] ?? "")) return argv[2];
  return argv.join(" ");
}

/** The command of a Codex code-mode script that only runs one `tools.exec_command({ cmd: "…" })`. */
function codeModeCommand(script: string): string | undefined {
  const calls = script.match(/\btools\.\w+\(/g);
  if (calls?.length !== 1 || calls[0] !== "tools.exec_command(") return undefined;
  const literal = /\btools\.exec_command\(\s*\{\s*"?cmd"?\s*:\s*("(?:[^"\\]|\\.)*")/.exec(script)?.[1];
  if (!literal) return undefined;
  try {
    return JSON.parse(literal) as string;
  } catch {
    return undefined;
  }
}

/**
 * The tool call as pi's own tool when there is one (bash, read, write, edit, apply_patch), so the transcript draws
 * it as pi would and a continuing model sees calls to the tools it has; other tools keep their name and arguments.
 */
export function mapToolCall(id: string, name: string, args: Record<string, unknown>): ToolCall {
  const call = (mapped: string, mappedArgs: Record<string, unknown>): ToolCall => ({ type: "toolCall", id, name: mapped, arguments: trimArguments(mappedArgs) });
  switch (name) {
    // Codex
    case "exec_command": {
      const command = str(args.cmd) ?? commandLine(args.command);
      if (command !== undefined) return call("bash", { command });
      break;
    }
    case "shell":
    case "local_shell":
    case "container.exec":
    case "shell_command": {
      const command = commandLine(args.command);
      if (command !== undefined) return call("bash", { command });
      break;
    }
    case "apply_patch":
      if (typeof args.input === "string") return call("apply_patch", { input: args.input });
      break;
    case "exec": {
      // Codex's code mode: a JS script calling its tools; one shell command reads best as that command.
      const command = typeof args.input === "string" ? codeModeCommand(args.input) : undefined;
      if (command !== undefined) return call("bash", { command });
      break;
    }
    // Claude Code
    case "Bash":
      if (typeof args.command === "string") return call("bash", { command: args.command });
      break;
    case "Read":
      if (typeof args.file_path === "string") return call("read", { path: args.file_path, ...(args.offset !== undefined && { offset: args.offset }), ...(args.limit !== undefined && { limit: args.limit }) });
      break;
    case "Write":
      if (typeof args.file_path === "string") return call("write", { path: args.file_path, content: str(args.content) ?? "" });
      break;
    case "Edit":
      if (typeof args.file_path === "string") return call("edit", { path: args.file_path, edits: [{ oldText: str(args.old_string) ?? "", newText: str(args.new_string) ?? "" }] });
      break;
    case "MultiEdit":
      if (typeof args.file_path === "string" && Array.isArray(args.edits)) {
        const edits = (args.edits as Record<string, unknown>[]).map((edit) => ({ oldText: str(edit?.old_string) ?? "", newText: str(edit?.new_string) ?? "" }));
        return call("edit", { path: args.file_path, edits });
      }
      break;
  }
  return call(name, args);
}

/** JSON arguments as an object; anything else as `{ input }`. */
export function parseArguments(raw: unknown): Record<string, unknown> {
  if (raw && typeof raw === "object" && !Array.isArray(raw)) return raw as Record<string, unknown>;
  if (typeof raw !== "string") return {};
  try {
    const value = JSON.parse(raw);
    if (value && typeof value === "object" && !Array.isArray(value)) return value as Record<string, unknown>;
  } catch {
    // free-form input (Codex custom tools: apply_patch, exec)
  }
  return { input: raw };
}

export async function forEachLimit<T>(items: T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> {
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (next < items.length) await fn(items[next++] as T);
    }),
  );
}

export function timeOf(value: unknown, fallback: number): number {
  const time = typeof value === "string" ? Date.parse(value) : typeof value === "number" ? value : Number.NaN;
  return Number.isFinite(time) ? time : fallback;
}

/**
 * Collects a chat's entries in pi's order: an answer's thinking, text and tool calls go in one assistant message,
 * which ends when tool results or the next user message come.
 */
export class EntryBuilder {
  readonly entries: ImportedEntry[] = [];
  private current: AssistantMessage | undefined;

  constructor(private readonly start: () => AssistantMessage) {}

  user(message: UserMessage | undefined): void {
    if (!message) return;
    this.flush();
    this.entries.push({ kind: "message", message });
  }

  /** A block of the running answer; `fresh` starts a new answer (another message id in Claude Code). */
  block(block: TextContent | ThinkingContent | ToolCall | undefined, fresh = false): void {
    if (!block) return;
    if (fresh) this.flush();
    this.current ??= this.start();
    this.current.content.push(block);
  }

  /** The model of the answer being built (Claude Code names it per message). */
  setModel(model: string | undefined): void {
    if (model && this.current) this.current.model = model;
  }

  result(message: ToolResultMessage): void {
    this.flush();
    this.entries.push({ kind: "message", message });
  }

  compaction(summary: string, timestamp: number): void {
    this.flush();
    this.entries.push({ kind: "compaction", summary, timestamp });
  }

  finish(): ImportedEntry[] {
    this.flush();
    return this.entries;
  }

  private flush(): void {
    const message = this.current;
    this.current = undefined;
    if (!message || message.content.length === 0) return;
    message.stopReason = message.content.at(-1)?.type === "toolCall" ? "toolUse" : "stop";
    this.entries.push({ kind: "message", message });
  }
}
